services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    http: false
    depends: mysql
    aliases:
      - preloaded
      - minimal
      - standard
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
      update: |
        set -eux
        export COMPOSER_MEMORY_LIMIT=-1

        # Create a Drupal 9 site with Tugboat config.
        git clone --branch 9.3.x --single-branch --quiet https://git.drupalcode.org/project/drupal.git drupal
        rm -rf drupal/.git

        # Moves all files (including dotfiles) to root of repository.
        cd drupal/ && find . -name . -o -exec sh -c 'mv -- "$@" "$0"' ../ {} + -type d -prune && cd ..
        rm -rf drupal/

        # Delete existing Drupal branch if exists.
        git branch -d 9.3.x || true
        git push origin --delete 9.3.x || true

        # Add Drupal to new branch, and push.
        git checkout -b 9.3.x
        git add .
        git commit -m "Adding Drupal 9."
        git push --force origin 9.3.x

        cp $TUGBOAT_ROOT/.tugboat/sites.php $TUGBOAT_ROOT/sites/sites.php

        # Install Drupal.
        ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
        cd $TUGBOAT_ROOT
        composer install --optimize-autoloader
        composer require drush/drush

        # Install Drupal on the minimal site.
        vendor/bin/drush \
          --yes \
          --uri=minimal \
          --db-url=mysql://tugboat:tugboat@mysql:3306/minimal \
          --site-name=Olivero \
          --account-pass=${ADMIN_PASSWORD} \
          site:install minimal
        chgrp -R www-data $DOCROOT/sites/minimal/files
        chmod 2775 $DOCROOT/sites/minimal/files
        chmod -R g+w $DOCROOT/sites/minimal/files

        # Install Drupal on the standard site.
        vendor/bin/drush \
          --yes \
          --uri=standard \
          --db-url=mysql://tugboat:tugboat@mysql:3306/standard \
          --site-name=Olivero \
          --account-pass=${ADMIN_PASSWORD} \
          site:install standard
        chgrp -R www-data $DOCROOT/sites/standard/files
        chmod 2775 $DOCROOT/sites/standard/files
        chmod -R g+w $DOCROOT/sites/standard/files

        # Install Drupal on the preloaded site. We're really only doing this to
        # get the site dir and settings.php file created properly.
        vendor/bin/drush \
          --yes \
          --uri=preloaded \
          --db-url=mysql://tugboat:tugboat@mysql:3306/preloaded \
          --site-name=Olivero \
          --account-pass=${ADMIN_PASSWORD} \
          site:install minimal

        # Import the database into preloaded.
        wget -O /tmp/olivero_db.sql.gz ${PRELOADED_DB_DUMP}
        zcat /tmp/olivero_db.sql.gz | vendor/bin/drush --uri=preloaded sql:cli
        rm /tmp/olivero_db.sql.gz

        # Set default theme for minimal and standard profiles.
        drush --uri=minimal theme:enable olivero
        drush --uri=minimal config:set system.theme default olivero
        drush --uri=standard theme:enable olivero
        drush --uri=standard config:set system.theme default olivero

        # Download the files for preloaded.
        wget -O /tmp/olivero_files.zip ${PRELOADED_FILES_ZIP}
        unzip -od $DOCROOT/sites/preloaded/files /tmp/olivero_files.zip
        chgrp -R www-data $DOCROOT/sites/preloaded/files
        chmod 2775 $DOCROOT/sites/preloaded/files
        chmod -R g+w $DOCROOT/sites/preloaded/files

        # Download Claro Tools
        wget -O /tmp/cd_tools.zip https://github.com/zolhorvath/cd_tools/archive/refs/tags/3.0.0.zip
        unzip -od $DOCROOT/modules/contrib /tmp/cd_tools.zip
        mv $DOCROOT/modules/contrib/cd_tools-3.0.0 $DOCROOT/modules/contrib/cd_tools

      build: |
        set -eux
        export COMPOSER_MEMORY_LIMIT=-1
        cd $TUGBOAT_ROOT
        composer install --optimize-autoloader
        composer require drush/drush
        composer require drupal/webform:^6
        composer require drupal/form_style
        composer require drupal/admin_toolbar
        composer require drupal/metatag
        composer require drupal/devel:^4
        composer require drupal/styleguide:2.x-dev@dev

        # Add composer files to git
        git add composer.json composer.lock
        git commit -m "Adding updated composer files." || true
        git push origin 9.3.x || true

        # Update the preloaded database and clear the cache.
        drush -y --uri=preloaded updatedb
        drush -y --uri=preloaded cache:rebuild

    visualdiffs:
      - /
      - /node/7
      - /node/6
      - /node/4
      - /node/1
      - /node/3
      - /node/31
      - /node/58
      - /node/59
      - /form/job-application
      - /form/registration
      - /form/session-evaluation
      - /form/user-profile
      - /grid-view
      - /table
      - /contact
      - /search/node?keys=drupal
      - /user/login
      - /user/register
      - /admin/appearance/styleguide/olivero
      - /appearance/form_style
      - /node/60
  mysql:
    image: tugboatqa/mariadb
    commands:
      update:
        - mysql -e "DROP DATABASE IF EXISTS preloaded; DROP DATABASE IF EXISTS minimal; DROP DATABASE IF EXISTS standard;"
        - mysql -e "CREATE DATABASE preloaded; CREATE DATABASE minimal; CREATE DATABASE standard;"
        - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'tugboat'; FLUSH PRIVILEGES;"
