services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
      update: |

        # Create a Drupal 9 site with Tugboat config.
        [ -d web ] && rm -rf web
        git clone https://git.drupalcode.org/project/drupal.git web
        cd web
        cp -R ../.tugboat .tugboat
        git add .tugboat
        git commit -m "Adding Tugboat config to Drupal 9"
        # git push --force main 9.2.x

        # Install Drupal.
        ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        composer install --optimize-autoloader
        composer require drush/drush
        composer require drupal/webform:6.0.0-alpha9 -vvv
        composer require drupal/admin_toolbar -vvv
        composer require drupal/metatag -vvv
        composer require drupal/devel:4.0.0 -vvv

        mkdir -p "${DOCROOT}/sites/default/files"
        chgrp -R www-data "${DOCROOT}/sites/default/files"
        find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;
        drush \
          --yes
          --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat \
          --account-name=admin \
          --account-pass=admin \
          --site-name=Olivero \
          site:install standard

        # Enable modules.
        drush en -y webform
        drush en -y admin_toolbar
        drush en -y metatag
        drush en -y devel

        # Enable olivero.
        drush theme:enable olivero
        drush config-set system.theme default olivero
        drush cache:rebuild

      build: |
        cd "${DOCROOT}"
        composer install --optimize-autoloader
        composer require drush/drush
        drush cache:rebuild
        drush config:import -y
        drush updatedb -y
        drush cache:rebuild

  mysql:
    image: tugboatqa/mariadb:10.5
    commands:
      update:
