services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    http: false
    depends: mysql
    aliases:
      - preloaded
      - minimal
      - standard
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
      update: |

        set -eux
        export COMPOSER_MEMORY_LIMIT=-1

        # Create a Drupal 9 site with Tugboat config.
        [ -d web ] && rm -rf web
        git clone --branch 9.1.x --single-branch https://git.drupalcode.org/project/drupal.git web
        pwd
        ls -la
        cp .tugboat/sites.php web/sites/sites.php
        cd web
        cp -R ../.tugboat .tugboat
        git add .tugboat
        git commit -m "Adding Tugboat config to Drupal 9"
        # git push --force main 9.2.x

        # Install Drupal.
        ln -snf "${TUGBOAT_ROOT}/web" "${DRUPAL_DOCROOT}"
        composer install --optimize-autoloader
        composer require drush/drush
        composer require drupal/webform:6.0.0-alpha9 -vvv
        composer require drupal/admin_toolbar -vvv
        composer require drupal/metatag -vvv
        composer require drupal/devel:4.0.0 -vvv

        # Install Drupal on the minimal site.
        vendor/bin/drush \
          --yes \
          --uri=minimal \
          --db-url=mysql://tugboat:tugboat@mysql:3306/minimal \
          --site-name=Olivero \
          --account-pass=${ADMIN_PASSWORD} \
          site:install minimal
        chgrp -R www-data $DRUPAL_DOCROOT/sites/minimal/files
        chmod 2775 $DRUPAL_DOCROOT/sites/minimal/files
        chmod -R g+w $DRUPAL_DOCROOT/sites/minimal/files

        # Install Drupal on the standard site.
        vendor/bin/drush \
          --yes \
          --uri=standard \
          --db-url=mysql://tugboat:tugboat@mysql:3306/standard \
          --site-name=Olivero \
          --account-pass=${ADMIN_PASSWORD} \
          site:install standard
        chgrp -R www-data $DRUPAL_DOCROOT/sites/standard/files
        chmod 2775 $DRUPAL_DOCROOT/sites/standard/files
        chmod -R g+w $DRUPAL_DOCROOT/sites/standard/files

        # Install Drupal on the preloaded site. We're really only doing this to
        # get the site dir and settings.php file created properly.
        vendor/bin/drush \
          --yes \
          --uri=preloaded \
          --db-url=mysql://tugboat:tugboat@mysql:3306/preloaded \
          --site-name=Olivero \
          --account-pass=${ADMIN_PASSWORD} \
          site:install minimal

        # Import the database into preloaded.
        wget -O /tmp/olivero_db.sql.gz ${PRELOADED_DB_DUMP}
        zcat /tmp/olivero_db.sql.gz | vendor/bin/drush --uri=preloaded sql:cli
        rm /tmp/olivero_db.sql.gz

        # Download the files for preloaded.
        wget -O /tmp/olivero_files.zip ${PRELOADED_FILES_ZIP}
        unzip -od $DRUPAL_DOCROOT/sites/preloaded/files /tmp/olivero_files.zip
        chgrp -R www-data $DRUPAL_DOCROOT/sites/preloaded/files
        chmod 2775 $DRUPAL_DOCROOT/sites/preloaded/files
        chmod -R g+w $DRUPAL_DOCROOT/sites/preloaded/files

      build: |
        set -eux
        export COMPOSER_MEMORY_LIMIT=-1
        cd $TUGBOAT_ROOT/web
        composer install --optimize-autoloader
        composer require drush/drush
        drush -y --uri=preloaded updatedb
        drush --uri=preloaded cache:rebuild
        drush -y --uri=minimal updatedb
        drush --uri=minimal cache:rebuild
        drush -y --uri=standard updatedb
        drush --uri=standard cache:rebuild

    visualdiffs:
      - /
      - /node/7
      - /node/6
      - /node/4
      - /node/1
      - /node/3
      - /form/job-application
      - /form/registration
      - /form/session-evaluation
      - /form/user-profile
      - /grid-view
      - /node/31
      - /table
      - /contact
      - /search/node?keys=drupal
      - /user/login
      - /user/register
  mysql:
    image: tugboatqa/mariadb
    commands:
      update:
        - mysql -e "DROP DATABASE IF EXISTS preloaded; DROP DATABASE IF EXISTS minimal; DROP DATABASE IF EXISTS standard;"
        - mysql -e "CREATE DATABASE preloaded; CREATE DATABASE minimal; CREATE DATABASE standard;"
        - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'tugboat'; FLUSH PRIVILEGES;"
